#
#  Script to replace the hard-copy manual figure with an on-line
#  version that may be animated and have a hyperlink to an on-line
#  database of output (LAS, ingrid etc....)
#
#  l2h creates figures in a table with a <CAPTION> element for the figure
#  legend. This script does the following on the l2h nodeNN.html 
#  (source originally generated by l2h) files.
#  1. Find a special rawhtml marker that brackets a figure to mark it
#     for replacement as follows
#     MITGCM_INSERT_FIGURE_BEGIN
#     figure to be replaced
#     MITGCM_INSERT_FIGURE_END
#  
#  2. Looks at the argument after MITGCM_INSERT_FIGURE_BEGIN which gives
#     the name of a directory where the replacement html is found e.g
#     MITGCM_INSERT_FIGURE_BEGIN ../on-line-figures/sio-adjoint/sio-adjoint.html
# 
#  3. Inserts this html in place of the html selected in 1.
#     The figure part is formatted
#     <TR><TD>......
#     .....</TD></TR>
#     within this part the attributes WIDTH= and HEIGHT=
#     may be useful.
#     A hyperlink for the figure image needs to be inserted within
#     the <TR><TD>....</TD></TR> section.
#     e.g. <TR><TD><A href=...><IMG ....></A></TD></TR>.
#
#  4. Optionally the script can take the full caption from the l2h document
#     or just the figure number.
#     The format of this section is
#     <CAPTION ALIGN="BOTTOM"><STRONG>Figure 2.13:</STRONG>
#     caption text....
#     caption text....
#     caption text....
#     caption text</CAPTION>
#    
#  5. Document tags for cross-referencing are also copied over from source.
#     These have the format <A NAME=""></A>. Figures can have several of these
#     one internal to l2h and one corresponding to the \label{} latex
#     attribute.
#     
#     
#
#
BEGIN{infigblok=0}
/MITGCM_INSERT_FIGURE_BEGIN/{ print "Figure html for " $2;infigblock=1}
{ if ( infigblock == 0 ) print }
/MITGCM_INSERT_FIGURE_END/{ infigblock=0}
END{}

